### ISSUE TITLE
Exception raised while handling cache file

### ISSUE THREAD

**Issue by VersteegenPeter** [LibreTranslate/LibreTranslate#629]
I get a constant flow of the following warnings  :

WARNING:root:Exception raised while handling cache file 'db/sessions/9593d4a70e9f5105d93c6923d473a85d'
Traceback (most recent call last):
  File "/home/mysd/translate/.venv/lib/python3.10/site-packages/cachelib/file.py", line 140, in _remove_older
    timestamp = struct.unpack("I", f.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes
WARNING:root:Exception raised while handling cache file 'db/sessions/d188e909f6e139e852204b60ca8f1ac5'
Traceback (most recent call last):
  File "/home/mysd/translate/.venv/lib/python3.10/site-packages/cachelib/file.py", line 140, in _remove_older
    timestamp = struct.unpack("I", f.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

**Comment by VersteegenPeter** [comment]
My collegue who programs python himself found out that the warning is caused by empty cache files. The program tries to read 4 bytes but it is unable to get 4 bytes because the cache file is empty. The problem can be (temporarely) resolved by deleting all cached files with the command rm db/sessions/* but the program creates new empty cache files during the translations. Hopefully this error can be corrected and the cache files will be cleaned up as normal.

**Comment by samuelyutt** [comment]
This bug is confirmed on Mac docker. The rm db/sessions/* did not solved the problem. New cache files under sessions/ will continuously be generated every second.

**Comment by pierotofy** [comment]
Should be fixed with #890. Thanks for the report!
