### ISSUE TITLE
bootup issue with 1.8.2 and 1.8.3

### ISSUE THREAD

**Issue by kabilesh13** [LibreTranslate/LibreTranslate#905]
**Deployment's health probe fails because of session data and pod keep restarting #889 **

base on the fix, we tried to upgrade the libretranslate version to 1.8.2 and 1.8.3 and with both facing similar startup issues with python file

error with 1.8.2:

```

░█░░░▀█▀░█▀▄░█▀▄░█▀▀░▀█▀░█▀▄░█▀█░█▀█░█▀▀░█░░░█▀█░▀█▀░█▀▀
░█░░░░█░░█▀▄░█▀▄░█▀▀░░█░░█▀▄░█▀█░█░█░▀▀█░█░░░█▀█░░█░░█▀▀
░▀▀▀░▀▀▀░▀▀░░▀░▀░▀▀▀░░▀░░▀░▀░▀░▀░▀░▀░▀▀▀░▀▀▀░▀░▀░░▀░░▀▀▀
v1.8.2

Booting...
Power cycling...
[2025-12-10 09:48:47 +0000] [108] [INFO] Starting gunicorn 23.0.0
[2025-12-10 09:48:49 +0000] [108] [INFO] Listening at: http://[::]:5000 (108)
[2025-12-10 09:48:49 +0000] [108] [INFO] Using worker: sync
[2025-12-10 09:48:49 +0000] [157] [INFO] Booting worker with pid: 157
[2025-12-10 09:48:50 +0000] [158] [INFO] Booting worker with pid: 158
[2025-12-10 09:48:50 +0000] [159] [INFO] Booting worker with pid: 159
[2025-12-10 09:48:50 +0000] [160] [INFO] Booting worker with pid: 160
[2025-12-10 09:52:06 +0000] [157] [ERROR] Error handling request /health
Traceback (most recent call last):
  File "/app/venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/app/venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/wsgi.py", line 17, in app
    instance = main()
               ^^^^^^
  File "/app/libretranslate/main.py", line 267, in main
    app = DispatcherMiddleware(create_app(args))
                               ^^^^^^^^^^^^^^^^
  File "/app/libretranslate/app.py", line 317, in create_app
    measure_request = Summary('libretranslate_http_request_duration_seconds', 'Time spent on request', ['endpoint', 'status', 'request_ip', 'api_key'])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/prometheus_client/metrics.py", line 143, in __init__
    registry.register(self)
  File "/app/venv/lib/python3.11/site-packages/prometheus_client/registry.py", line 43, in register
    raise ValueError(
ValueError: Duplicated timeseries in CollectorRegistry: {'libretranslate_http_request_duration_seconds_sum', 'libretranslate_http_request_duration_seconds_created', 'libretranslate_http_request_duration_seconds', 'libretranslate_http_request_duration_seconds_count'}
```

error with 1.8.3:

```

░█░░░▀█▀░█▀▄░█▀▄░█▀▀░▀█▀░█▀▄░█▀█░█▀█░█▀▀░█░░░█▀█░▀█▀░█▀▀
░█░░░░█░░█▀▄░█▀▄░█▀▀░░█░░█▀▄░█▀█░█░█░▀▀█░█░░░█▀█░░█░░█▀▀
░▀▀▀░▀▀▀░▀▀░░▀░▀░▀▀▀░░▀░░▀░▀░▀░▀░▀░▀░▀▀▀░▀▀▀░▀░▀░░▀░░▀▀▀
v1.8.3

Booting...
Power cycling...
[2025-12-10 09:37:53 +0000] [110] [INFO] Starting gunicorn 23.0.0
[2025-12-10 09:37:55 +0000] [110] [INFO] Listening at: http://0.0.0.0:5000 (110)
[2025-12-10 09:37:55 +0000] [110] [INFO] Using worker: sync
[2025-12-10 09:37:55 +0000] [159] [INFO] Booting worker with pid: 159
[2025-12-10 09:37:55 +0000] [160] [INFO] Booting worker with pid: 160
[2025-12-10 09:37:55 +0000] [161] [INFO] Booting worker with pid: 161
[2025-12-10 09:37:55 +0000] [162] [INFO] Booting worker with pid: 162
[2025-12-10 09:41:15 +0000] [159] [ERROR] Error handling request /health
Traceback (most recent call last):
  File "/app/venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/app/venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/wsgi.py", line 17, in app
    instance = main()
               ^^^^^^
  File "/app/libretranslate/main.py", line 267, in main
    app = DispatcherMiddleware(create_app(args))
                               ^^^^^^^^^^^^^^^^
  File "/app/libretranslate/app.py", line 317, in create_app
    measure_request = Summary('libretranslate_http_request_duration_seconds', 'Time spent on request', ['endpoint', 'status', 'request_ip', 'api_key'])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/prometheus_client/metrics.py", line 143, in __init__
    registry.register(self)
  File "/app/venv/lib/python3.11/site-packages/prometheus_client/registry.py", line 43, in register
    raise ValueError(
ValueError: Duplicated timeseries in CollectorRegistry: {'libretranslate_http_request_duration_seconds_created', 'libretranslate_http_request_duration_seconds_count', 'libretranslate_http_request_duration_seconds_sum', 'libretranslate_h
```ttp_request_duration_seconds'}

**Comment by resuarez** [comment]
I have the same problem with v1.8.3 using unraid. I didn't try with v1.8.2.  Using v1.8.1, it works for me.

**Comment by epcos71** [comment]
same problem here using v1.8.3. Seems to be a permission issue with gunicorn:

>PermissionError: [Errno 13] Permission denied: '/nonexistent'
>
>usage: gunicorn [OPTIONS] [APP_MODULE]
>
>gunicorn: error: argument -w/--workers: expected one argument`

**Comment by pierotofy** [comment]
Must have been broken with https://github.com/LibreTranslate/LibreTranslate/commit/b17d58d71c830630bd05c78bb59beeb1515ba33a

For whatever reason, the $HOME env variable is no longer set.

**Comment by TheTakylo** [comment]
So there's also a problem with the tests that shouldn't have worked

**Comment by pierotofy** [comment]
`PermissionError` should be fixed with https://github.com/LibreTranslate/LibreTranslate/commit/00d01a99d76041ded4543880a4c5815cba49a799
`ValueError` should be fixed with https://github.com/LibreTranslate/LibreTranslate/commit/296e53e5113cc5ff60fa273a952b87013eb18b9f

Update and try again? 🙏  If the issue persists we can re-open.

Thanks for the reports.

**Comment by kabilesh13** [comment]
@pierotofy im using official image from dockerhub, can you please release the newer version with fix?

**Comment by momonator25** [comment]
The problem is not resolved. Please reopen the issue.

Tried to update from `1.8.0` to `1.8.3` and got `ValueError: Duplicated timeseries...`
Also tried:  `1.8.2` with same results. Rolled back to `1.8.1` which seems to be the latest working version.

**Comment by pierotofy** [comment]
Did you try the `latest` image?

**Comment by momonator25** [comment]
> Did you try the `latest` image?

I never use `latest` tags so i missed the update.
Can confirm `sha256:b1001fa46eda1265fb9681d03902c294fe2a705680c283aebd5d916e02d6aae0` does solve the problem.
Just need to revert the tag to default scheme when it's merged into tagged version.
Thanks for your fast reply!
